blueprints/ddos.py
import os
from datetime import datetime
from flask import Blueprint, render_template, request, redirect, url_for, flash
from pymisp import PyMISP, MISPEvent, MISPAttribute
from misp_connect import get_api_key_for_org, get_available_organisations

ddos_bp = Blueprint('ddos', __name__, template_folder='templates')

@ddos_bp.route('/ddos', methods=['GET', 'POST'])
def ddos():
    MISP_URL = os.getenv('MISP_URL')
    MISP_VERIFY_SSL = os.getenv('MISP_VERIFY_SSL', 'False').lower() == 'true'
    available_organisations = get_available_organisations()  # Get list dynamically


    if request.method == 'POST':
        selected_org = request.form.get('organisation')
        MISP_API_KEY = get_api_key_for_org(selected_org)

        if not MISP_API_KEY:
            flash("Invalid organisation selected. Please try again.", "danger")
            return redirect(url_for('ddos.ddos'))

        misp = PyMISP(MISP_URL, MISP_API_KEY, MISP_VERIFY_SSL)

        try:
            # Collect form data
            source_ips = request.form.get('source_ip', '').split(',')
            target_ip = request.form.get('target_ip')
            target_url = request.form.get('target_url')
            port = request.form.get('port')
            duration = request.form.get('duration')
            protocol = request.form.get('protocol')
            attack_type = request.form.get('attack_type')
            description = request.form.get('description')
            threat_actor = request.form.get('threat_actor')
            date = request.form.get('date', datetime.today().strftime('%Y-%m-%d'))
            time = request.form.get('time')
            tlp = request.form.get('tlp')

            distribution = int(request.form.get('distribution', 0))
            threat_level_id = int(request.form.get('threat_level_id', 4))
            analysis = int(request.form.get('analysis', 0))

            if not target_ip and not target_url:
                flash("Either a target IP or target URL must be provided.", "danger")
                return redirect(url_for('ddos.ddos'))


            # Create MISP event
            misp_event = MISPEvent()
            misp_event.info = f"DDoS Attack Report - {target_ip or target_url}"
            misp_event.distribution = distribution
            misp_event.threat_level_id = threat_level_id
            misp_event.analysis = analysis

            if tlp:
                misp_event.add_tag(tlp)

            misp_event.add_tag('rsit:availability="ddos"')
            misp_event.add_tag('rsit:availability="dos"')
            misp_event.add_tag('circl:incident-classification="denial-of-service"')            
            misp_event.add_tag('source:UnderServed')
            misp_event.add_tag('source:MISP-Forms')
            misp_event.add_tag('misp-galaxy:mitre-attack-pattern="Network Denial of Service - T1498"')  # ddos

            event = misp.add_event(misp_event)
            event_id = event['Event']['id']

            # Add attributes
            for ip in source_ips:
                ip = ip.strip()
                if ip:
                    add_attribute(misp, event_id, category="Network activity", type="ip-src", value=ip)

            if target_ip:
                add_attribute(misp, event_id, category="Network activity", type="ip-dst", value=target_ip)
            if target_url:
                add_attribute(misp, event_id, category="Network activity", type="domain", value=target_url)
            if port:
                add_attribute(misp, event_id, category="Network activity", type="dst-port", value=port)
            if duration:
                add_attribute(misp, event_id, category="Other", type="text", value=f"{duration} minutes", comment="Duration of the attack")
            if protocol: ## not an MISP atribute - find alternative
                add_attribute(misp, event_id, category="Network activity", type="protocol", value=protocol)
            if attack_type:
                add_attribute(misp, event_id, category="Network activity", type="pattern-in-traffic", value=attack_type, comment="Attack Type")
            if description:
                add_attribute(misp, event_id, category="Other", type="text", value=description, comment="Description of Event")
            if threat_actor:
                add_attribute(misp, event_id, category="Attribution", type="threat-actor", value=threat_actor)
            if time:
                add_attribute(misp, event_id, category="Other", type="datetime", value=f"{date} {time}",
                              comment="Date and Time of Attack")

            flash(
                '✅ Report submitted successfully - Thank you!',
                'light')
            #
            return redirect(url_for('ddos.ddos'))
        except Exception as e:
            flash(f"An error occurred: {e}", "danger")
            return redirect(url_for('ddos.ddos'))

    return render_template('ddos.html', available_organisations=available_organisations, today_date=datetime.today().strftime('%Y-%m-%d'))


def add_attribute(misp, event_id, category, type, value, comment=None):
    attribute = MISPAttribute()
    attribute.category = category
    attribute.type = type
    attribute.value = value
    if comment:
        attribute.comment = comment
    misp.add_attribute(event_id, attribute)

blueprints/phishing.py
import os
import base64
import hashlib
from datetime import datetime
from flask import Blueprint, render_template, request, redirect, url_for, flash
from pymisp import PyMISP, MISPEvent, MISPAttribute
from werkzeug.utils import secure_filename
from misp_connect import get_api_key_for_org, get_available_organisations  # Import from misp_connect

phishing_bp = Blueprint('phishing', __name__, template_folder='../templates')

@phishing_bp.route('/phishing_choice')
def phishing_choice():
    return render_template('phishing_choice.html')


@phishing_bp.route('/phishing', methods=['GET', 'POST'])
def phishing():
    available_organisations = get_available_organisations()

    if request.method == 'POST':
        try:
            selected_org = request.form.get('organisation')
            MISP_API_KEY = get_api_key_for_org(selected_org)

            if not MISP_API_KEY:
                flash("Invalid organisation selected. Please try again.", "danger")
                return redirect(url_for('phishing.phishing'))

            MISP_URL = os.getenv('MISP_URL')
            MISP_VERIFY_SSL = os.getenv('MISP_VERIFY_SSL', 'False').lower() == 'true'
            misp = PyMISP(MISP_URL, MISP_API_KEY, MISP_VERIFY_SSL)

            email_sender = request.form.get('email_sender')
            subject = request.form.get('subject')
            body = request.form.get('body')
            urls = request.form.get('urls', '').splitlines()
            attachment = request.files.get('attachment')
            date = request.form.get('date', datetime.today().strftime('%Y-%m-%d'))

            if not email_sender or not subject:
                flash("Email sender and subject are required fields.", "danger")
                return redirect(url_for('phishing.phishing'))

            # Create MISP event
            misp_event = MISPEvent()
            misp_event.info = f"Phishing Email Report - {subject}"
            misp_event.date = date
            misp_event.distribution = int(request.form.get('distribution', 0))
            misp_event.threat_level_id = int(request.form.get('threat_level_id', 4))
            misp_event.analysis = int(request.form.get('analysis', 2))
            misp_event.add_tag('rsit:fraud="phishing"')
            misp_event.add_tag('circl: incident - classification = "phishing"')
            misp_event.add_tag('tlp:red')  # currently fixed, not changed by sharing option on form
            misp_event.add_tag('source:UnderServed')
            misp_event.add_tag('source:MISP-Forms')
            misp_event.add_tag('misp-galaxy:mitre-attack-pattern="Phishing - T1660"')  # phishing
            misp_event.add_tag('misp-galaxy:mitre-attack-pattern="Phishing for Information - T1598"')  # phishing

            event = misp.add_event(misp_event)
            event_id = event['Event']['id']

            # map arributes from form inputs
            add_attribute(misp, event_id, category="Payload delivery", attr_type="email-src", value=email_sender, comment="Phishing Email Sender")
            add_attribute(misp, event_id, category="Payload delivery", attr_type="email-subject", value=subject, comment="Email Subject")
            add_attribute(misp, event_id, category="Payload delivery", attr_type="text", value=body, comment="Email Body Content")

            # Add URLs if found
            for url in urls:
                if url.strip():
                    add_attribute(misp, event_id, category="Network activity", attr_type="url", value=url.strip(), comment="Extracted URL from Email")

            # get attacments
            if attachment and attachment.filename != '':
                process_uploaded_file(misp, event_id, attachment, category="Payload delivery", attr_type="attachment", comment="Phishing Email Attachment")
                # get SHA256
                file_path = f"/tmp/{attachment.filename}"
                attachment.save(file_path)
                sha256_hash = hashlib.sha256()
                with open(file_path, "rb") as f:
                    for chunk in iter(lambda: f.read(4096), b""):
                        sha256_hash.update(chunk)
                attachment_sha256 = sha256_hash.hexdigest()
                add_attribute(misp, event_id, category="Payload delivery", attr_type="sha256", value=attachment_sha256, comment="SHA256 of Email Attachment")

            flash(
                '✅ Report submitted successfully - Thank you!',
                'light')
            return redirect(url_for('phishing.phishing'))

        except Exception as e:
            flash(f"An error occurred: {e}", "danger")
            return redirect(url_for('phishing.phishing'))

    return render_template('phishing.html', available_organisations=available_organisations, today_date=datetime.today().strftime('%Y-%m-%d'))


def add_attribute(misp, event_id, category, attr_type, value, data=None, comment=None):
    attribute = MISPAttribute()
    attribute.category = category
    attribute.type = attr_type
    attribute.value = value
    if data:
        attribute.data = data  # Attach file content if needed
    if comment:
        attribute.comment = comment
    response = misp.add_attribute(event_id, attribute)
    return response


def process_uploaded_file(misp, event_id, file, category, attr_type, comment):
    filename = secure_filename(file.filename)
    file_content = file.read()

    md5_hash = hashlib.md5(file_content).hexdigest()
    sha256_hash = hashlib.sha256(file_content).hexdigest()
    sha512_hash = hashlib.sha512(file_content).hexdigest()
    encoded_data = base64.b64encode(file_content).decode('utf-8')

    add_attribute(misp, event_id, category, attr_type="filename", value=filename, comment=f"{comment} Filename")
    add_attribute(misp, event_id, category, attr_type="md5", value=md5_hash, comment=f"{comment} MD5 Hash")
    add_attribute(misp, event_id, category, attr_type="sha256", value=sha256_hash, comment=f"{comment} SHA256 Hash")
    add_attribute(misp, event_id, category, attr_type="sha512", value=sha512_hash, comment=f"{comment} SHA512 Hash")


    add_attribute(misp, event_id, category, attr_type="attachment", value=filename, data=encoded_data, comment=f"{comment} Attachment Uploaded")


# limit file types,  add more to list if required,  avoid exes.  These should be handled with Pandora
def allowed_attachment_file(filename):
    allowed_extensions = {'eml', 'pdf', 'docx', 'xlsx', 'zip', 'rar'}
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in allowed_extensions

blueprints/scam_website.py
from flask import Blueprint, render_template, request, redirect
from pylookyloo import Lookyloo
from dotenv import load_dotenv
import os

load_dotenv()

# Initialise Lookyloo (this is lookyloo instance running on underserved platform
lookyloo_url = os.getenv('LOOKYLOO_URL')
lookyloo = Lookyloo(lookyloo_url)
lookyloo.session.verify = False

scam_website_bp = Blueprint('scam_website', __name__, template_folder='../templates')

@scam_website_bp.route('/scam-website', methods=['GET', 'POST'])
def scam_website():
    if request.method == 'POST':
        url = request.form['url']
        if lookyloo.is_up:
            try:
                permaurl = lookyloo.enqueue(url)
                return redirect(permaurl)
            except Exception as e:
                return f"An error occurred: {e}", 500
        else:
            return "Lookyloo instance is not reachable.", 503
    return render_template('scam-website.html')

blueprints/typo_squatting.py
from flask import Blueprint, render_template, request, redirect, flash
from pylookyloo import Lookyloo
from pymisp import ExpandedPyMISP, MISPEvent, MISPObject
import threading, subprocess, os, json
from dotenv import load_dotenv


load_dotenv()

# Initialise Lookyloo (this is lookyloo instance running on underserved platform
lookyloo_url = os.getenv('LOOKYLOO_URL')
lookyloo = Lookyloo(lookyloo_url)
lookyloo.session.verify = False

# MISP setup
misp_url = 'https://misp.underserved.org'
misp_key = 'misp-org1-apikey'
verify_cert = False
tld_file = './dictionaries/common_tlds.dict'
output_file = '/tmp/data.json'

typo_squatting_bp = Blueprint('typo_squatting', __name__, template_folder='../templates')

@typo_squatting_bp.route('/typo-squatting', methods=['GET', 'POST'])
def typo_squatting():
    if request.method == 'POST':
        url = request.form.get('url')
        domain = request.form.get('domain')

        if url:
            if lookyloo.is_up:
                try:
                    permaurl = lookyloo.enqueue(url)
                    return redirect(permaurl)
                except Exception as e:
                    return f"An error occurred: {e}", 500
            else:
                return "Lookyloo instance is not reachable.", 503

        if domain:
            threading.Thread(target=process_domain_task, args=(domain,)).start()
            flash( '🔍 The detection process is now running... If a potential typo-squatting site is detected, an event will be reported to <a href="https://misp.underserved.org" target="_blank">MISP</a>',
                'light')
    return render_template('typo-squatting.html')


def process_domain_task(domain):
    try:
        subprocess.run([
            "dnstwist",
            "--fuzzers", "tld-swap",
            "--tld", f"{tld_file}",
            "--lsh",
            "--format", "json", "-r", "-w", domain
        ], stdout=open(output_file, "w"), check=True)
    except subprocess.CalledProcessError:
        print("Failed to run dnstwist command.")
        return

    misp = ExpandedPyMISP(url=misp_url, key=misp_key, ssl=verify_cert)

    with open(output_file, 'r') as f:
        entries = json.load(f)

    event = MISPEvent()
    event.info = f"Potential Typo-Squatting on {domain}"
    event.distribution = 0
    event.threat_level_id = 2
    event.analysis = 0
    event.add_tag("tlp:red")
    event.add_tag('rsit:fraud="masquerade"')
    event.add_tag('type:Typo-Squatting')
    event.add_tag('source:UnderServed')
    event.add_tag('source:MISP-Forms"')


    added_domains = 0

    for entry in entries:
        if 'ssdeep' not in entry or entry['ssdeep'] <= 5:
            continue

        domain_obj = MISPObject(name='domain-ip')
        domain_obj.add_attribute('domain', type='domain', value=entry['domain'])

        for ip in entry.get('dns_a', []):
            domain_obj.add_attribute('ip', type='ip-dst', value=ip)

        for ip6 in entry.get('dns_aaaa', []):
            domain_obj.add_attribute('ip', type='ip-dst', value=ip6)

        for ns in entry.get('dns_ns', []):
            domain_obj.add_attribute('nameserver', type='hostname', value=ns)

        if 'fuzzer' in entry:
            domain_obj.add_attribute('fuzzer', type='text', value=entry['fuzzer'], comment='Fuzzing technique used')

        if 'geoip' in entry:
            domain_obj.add_attribute('geoip-location', type='text', value=entry['geoip'], comment='GeoIP resolved country')

        if 'whois_created' in entry:
            domain_obj.add_attribute('first-seen', type='datetime', value=entry['whois_created'], comment='WHOIS creation date')

        if 'whois_registrar' in entry:
            domain_obj.add_attribute('registrar', type='whois-registrar', value=entry['whois_registrar'])

        domain_obj.add_attribute('similarity-score', type='text', value=str(entry['ssdeep']), comment='SSDEEP similarity score')

        event.add_object(domain_obj)
        added_domains += 1

    if added_domains > 0:
        misp.add_event(event)
        print(f" Created MISP event with {added_domains} suspicious domains for {domain}")
    else:
        print(f" No suspicious domains (ssdeep > 5) found for {domain}")

templates/ddos.html
{% extends "base.html" %}

{% block title %}MISP-FORMS{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2><i class="fa-solid fa-robot"></i> Report a Denial-of-Service (DoS/DDoS) Attack</h2>
    <p class="info-box">
        A DoS (Denial of Service) attack is a malicious attempt to disrupt the normal functioning of a targeted server,
        service, or network by overwhelming it with a flood of illegitimate requests. This excessive load exhausts the
        system's resources, causing slowdowns, crashes, or complete inaccessibility to legitimate users.

        A DDoS (Distributed Denial of Service) attack amplifies this impact by using multiple compromised systems, often
        part of a botnet, to launch the attack simultaneously from various locations. This makes it harder to block and
        identify the source of the traffic, creating a more severe disruption. Both attacks aim to interrupt service
        availability, often for financial, political, or personal motives.

    </p>


    <!-- Flash Messages -->
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
      <div class="flash-message {{ category }}">
        {{ message|safe }}
      </div>
    {% endfor %}
  {% endif %}
{% endwith %}

    <form method="POST" action="/ddos">


        <!-- organisation Selection -->
        <h5>Organisation</h5>
        <div class="mb-3 p-3 border rounded" style="border: 2px solid #178f8f;">
            <label for="organisation" class="form-label">Select organisation (Required)</label>
            <select class="form-control" name="organisation" id="organisation" required>
                <option value="" disabled selected>Select an organisation</option>
                {% for org in available_organisations %}
                <option value="{{ org }}">{{ org }}</option>
                {% endfor %}
            </select>
        </div>


        <!-- Sharing Options -->
<h5>Sharing Options</h5>


        <div class="mb-3 p-3 border rounded" style="border: 2px solid #178f8f;">
            {% include 'event_sharing_lite.html' %}
        </div>


        <h5>Incident Details {% with href="https://mkdocs.underserved.org" %} {% include 'help.html' %} {% endwith %}</h5>
        <div class="mb-3 p-3 border rounded" style="border:2px solid #178f8f;">
                    <div class="row">
                <!-- Date -->
                <div class="col-md-6 mb-3">
                    <label for="date" class="form-label">Date of Attack: (Required)</label>
                    <input type="date" class="form-control" name="date" id="date" value="{{ today_date }}" required>
                </div>

                <!-- Time -->
                <div class="col-md-6 mb-3">
                    <label for="time" class="form-label">Time of Attack:</label>
                    <input type="time" class="form-control" name="time" id="time" required>
                </div>
            </div>


            <!-- Source IP -->
            <div class="mb-3">
                <label for="source_ip" class="form-label">Source or Attacker IP(s) (Required)</label>
                <input type="text" class="form-control" id="source_ip" name="source_ip" placeholder="Enter attacker IPs, separated by commas (e.g., 192.168.1.1, 10.0.0.1)" required pattern="(?:\d{1,3}\.\,){3}\d{1,3}"  inputmode="numeric"  placeholder="e.g. 192.168.1.1">
            </div>

            <!-- Target IP -->
            <div class="mb-3">
                <label for="target_ip" class="form-label">Target IP (Required)</label>
                <input type="text" class="form-control" id="target_ip" name="target_ip" required pattern="(?:\d{1,3}\.){3}\d{1,3}"  inputmode="numeric"  placeholder="e.g. 192.168.1.1">
            </div>

            <!-- Target URL -->
            <div class="mb-3">
                <label for="target_url" class="form-label">Target Domain</label>
                <input type="text" class="form-control" id="target_url" name="target_url" placeholder="Enter the target domain (e.g., example.com)">
            </div>

            <!-- Destination Port -->
            <div class="mb-3">
                <label for="port" class="form-label">Target Port</label>
                <select class="form-control" id="port" name="port">
                    <option value="20">20 (FTP - Data)</option>
                    <option value="21">21 (FTP - Control)</option>
                    <option value="22">22 (SSH)</option>
                    <option value="23">23 (Telnet)</option>
                    <option value="25">25 (SMTP)</option>
                    <option value="53">53 (DNS)</option>
                    <option value="80">80 (HTTP)</option>
                    <option value="123">123 (NTP)</option>
                    <option value="389">389 (LDAP)</option>
                    <option value="443">443 (HTTPS)</option>
                    <option value="445">445 (SMB)</option>
                    <option value="1900">1900 (SSDP)</option>
                    <option value="3306">3306 (MySQL)</option>
                    <option value="3389">3389 (RDP)</option>
                    <option value="5060">5060 (SIP)</option>
                    <option value="11211">11211 (Memcached)</option>
                </select>
            </div>


            <!-- Protocol -->
            <div class="form-group">
                <label for="protocol">Protocol:</label>
                <select class="form-control" id="protocol" name="protocol">
                    <option value="TCP">TCP</option>
                    <option value="UDP">UDP</option>
                    <option value="ICMP">ICMP</option>
                    <option value="IP">IP</option>
                </select>
            </div>

            <!-- Attack Type -->
            <div class="form-group">
                <label for="attack_type">Attack Type:</label>
                <select class="form-control" id="attack_type" name="attack_type">
                    <option value="amplification-attack">Amplification Attack</option>
                    <option value="reflected-spoofed-attack">Reflected Spoofed Attack</option>
                    <option value="slow-read-attack">Slow Read Attack</option>
                    <option value="flooding-attack">Flooding Attack</option>
                    <option value="post-attack">Post Attack</option>
                    <option value="dns">DNS</option>
                    <option value="tcp-syn">TCP SYN</option>
                    <option value="udp">UDP</option>
                </select>
            </div>


                        <!-- Threat Actor -->
            <div class="mb-3">
                <label for="threat_actor" class="form-label">Threat Actor</label>
                <div class="input-group">
                    <input type="text" class="form-control" id="threat_actor" name="threat_actor" placeholder="Enter Threat Actor name (optional)">
                    <a href="https://attack.mitre.org/groups/" class="btn btn-outline-info" target="_blank" rel="noopener noreferrer">
                        <img src="{{ url_for('static', filename='images/threat_actor.png') }}" alt="CVE" style="height: 22px; width: 22px; margin-right: 5px;"> Threat Actors
                    </a>
                </div>
            </div>

            <!-- Description -->
            <div class="mb-3">
                <label for="description" class="form-label">Description (Required)</label>
                <textarea class="form-control" id="description" name="description" rows="4" placeholder="Provide a description of the incident." required></textarea>
            </div>

            <!-- Spinner -->
            {% include 'spinner.html' %}

        </div>

        <!-- Submit Button -->
        <div class="text-center">
            <button type="submit" class="btn custom-btn">Submit Report</button>
        </div>

    </form>
</div>

{% endblock %}

templates/event_sharing.html
<html>
<head>
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}" />
</head>

<p>The default sharing options below are appropriate for most reports but please modify as necessary. If required, the platform administrator will adjust these values after submission.</p>

<hr style="border: none; height: 2px; background-color: gray;">

<div class="mb-3">
    <label for="distribution" class="form-label">Distribution</label>
    <select class="form-control" name="distribution" id="distribution">
        <option value="1" selected>This Community Only</option>
        <option value="2">Connected Communities</option>
        <option value="0">Your Organisation Only</option>
        <option value="3">All Communities</option>
    </select>
</div>

<!-- Threat Level -->
<div class="mb-3">
    <label for="threat_level_id" class="form-label">Threat Level  (Required)</label>
    <select class="form-control" name="threat_level_id" id="threat_level_id" required>
        <option value="4" selected>Undefined</option>
        <option value="1">High</option>
        <option value="2">Medium</option>
        <option value="3">Low</option>
    </select>
</div>

<!-- Analysis -->
<div class="mb-3">
    <label for="analysis" class="form-label">Analysis (Required)</label>
    <select class="form-control" name="analysis" id="analysis" required>
        <option value="0" selected>Initial</option>
        <option value="1">Ongoing</option>
        <option value="2">Completed</option>
    </select>
</div>

<!-- TLP -->
<div class="form-group">
  <label for="tlp">Traffic Light Protocol (TLP):</label>
    <select class="form-control" id="tlp" name="tlp" onchange="updateTLPBackground(this)">
      <option value="TLP:GREEN" selected>TLP:GREEN - Limited disclosure to the community</option>
      <option value="TLP:RED" style="background-color: #ffcccc;">TLP:RED - For recipient(s) only</option>
      <option value="TLP:AMBER" style="background-color: #fff4cc;">TLP:AMBER - Limited disclosure to those who need to know</option>
      <option value="TLP:WHITE" style="background-color: #ffffff;">TLP:WHITE - Public information</option>
    </select>
</div>

</html>

templates/index.html
{% extends "base.html" %}

{% block title %}MISP-FORMS{% endblock %}

{% block content %}

<div class="container mt-4" >
    <div class="row">
        <div class="col-md-6">
                                    <div class="menu-btn mb-3">
    <a href="{{ url_for('phishing.phishing_choice') }}" class="btn btn-blue btn-lg btn-block">
        <i class="fas fa-at"></i> Phishing Email
    </a>
</div>
                                    <div class="menu-btn mb-3">
    <a href="{{ url_for('smishing.smishing') }}" class="btn btn-blue btn-lg btn-block">
        <i class="fa-regular fa-message"></i> Smishing - Scam Text Message
    </a>
</div>
<div class="menu-btn mb-3">
    <a href="{{ url_for('xss.xss') }}" class="btn btn-blue btn-lg btn-block">
        <i class="fas fa-shuffle"></i> Cross Site Scripting (XSS)
    </a>
</div>
<div class="menu-btn mb-3">
    <a href="{{ url_for('typo_squatting.typo_squatting') }}" class="btn btn-blue btn-lg btn-block">
        <i class="fas fa-house-crack"></i> Typo-Squatting
    </a>
</div>
            <div class="menu-btn mb-3">
    <a href="{{ url_for('scam_website.scam_website') }}" class="btn btn-blue btn-lg btn-block">
        <i class="fas fa-triangle-exclamation"></i> Scam or Suspicious Website
    </a>
</div>

            <div class="menu-btn mb-3">
    <a href="{{ url_for('malware.malware') }}" class="btn btn-blue btn-lg btn-block">
        <i class="fas fa-virus"></i> Malware
    </a>
</div>

            <div class="menu-btn mb-3">
    <a href="{{ url_for('disinformation.disinformation') }}" class="btn btn-blue btn-lg btn-block">
        <i class="fas fa-bullhorn"></i> Disinformation
    </a>
</div>

                        <div class="menu-btn mb-3">
    <a href="{{ url_for('social_eng.social_eng') }}" class="btn btn-blue btn-lg btn-block">
        <i class="fas fa-people-arrows"></i> Social Engineering
    </a>
</div>

                                                                                    <div class="menu-btn mb-3">
    <a href="{{ url_for('password_attack.password_attack') }}" class="btn btn-blue btn-lg btn-block">
        <i class="fas fa-key"></i> Password Attack
    </a>
</div>

        </div>



        <div class="col-md-6">

            <div class="menu-btn mb-3">
    <a href="{{ url_for('defacement.web_defacement') }}" class="btn btn-blue btn-lg btn-block">
        <i class="fa-solid fa-skull-crossbones"></i> Website Defacement
    </a>
</div>

            <div class="menu-btn mb-3">
    <a href="{{ url_for('ddos.ddos') }}" class="btn btn-blue btn-lg btn-block">
        <i class="fa-solid fa-robot"></i> Denial-of-Service (DoS/DDoS)
    </a>
</div>

                                    <div class="menu-btn mb-3">
    <a href="{{ url_for('quishing.quishing') }}" class="btn btn-blue btn-lg btn-block">
        <i class="fas fa-qrcode"></i> Quishing - Scam QR Code
    </a>
</div>

                                    <div class="menu-btn mb-3">
    <a href="{{ url_for('invoice.invoice_diversion') }}" class="btn btn-blue btn-lg btn-block">
        <i class="fas fa-receipt"></i> Invoice Diversion Fraud
    </a>
</div>

                                                <div class="menu-btn mb-3">
    <a href="{{ url_for('sql_injection.sql_injection') }}" class="btn btn-blue btn-lg btn-block">
        <i class="fas fa-syringe"></i> SQL Injection
    </a>
</div>

                                                            <div class="menu-btn mb-3">
    <a href="{{ url_for('ransomware.ransomware') }}" class="btn btn-blue btn-lg btn-block">
        <i class="fa-brands fa-bitcoin"></i> Ransomware
    </a>
</div>


                                                            <div class="menu-btn mb-3">
    <a href="{{ url_for('mitm.mitm') }}" class="btn btn-blue btn-lg btn-block">
        <i class="fas fa-users"></i> Man-in-the-Middle
    </a>
</div>


                                                                        <div class="menu-btn mb-3">
    <a href="{{ url_for('vishing.vishing') }}" class="btn btn-blue btn-lg btn-block">
        <i class="fas fa-phone"></i> Vishing (Voice Phishing)
    </a>
</div>
                                                            <div class="menu-btn mb-3">
    <a href="{{ url_for('dynamic_form.dynamic_form') }}" class="btn btn-blue btn-lg btn-block">
        <i class="fas fa-list-check"></i> Custom Report (Advanced User)
    </a>
</div>


        </div>
    </div>
</div>


{% endblock %}

templates/support.html
{% extends "base.html" %}

{% block title %}MISP-FORMS{% endblock %}

{% block content %}

{% filter markdown %}
## HELLO CLEVELAND!
=============
{% endfilter %}

{% endblock %}